version: 2.1

workflows:
  build-and-create-apk:
    name: Build and Create APK
    environment:
      node: 16
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install -g expo-cli eas-cli
          npm install
      - name: Build APK
        script: |
          eas build -p android
    artifacts:
      - build/app/outputs/apk/release/*.apk
