yaml
workflows:
  version: 2

  build-and-create-apk:
    name: Build and Create APK
    scripts:
      - name: Install dependencies
        script: |
          npm install -g expo-cli
          npm install
      - name: Build APK
        script: |
          expo build:android -t apk
    artifacts:
      - build/app/outputs/apk/release/*.apk
