version: 2.1

workflows:
  build-and-create-apk:
    name: Build and Create APK
    environment:
      node: 16
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install -g react-native-cli
          npm install
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
